
jobs:
- job: PyPi_Linux
  pool:
   vmImage: 'ubuntu-18.04'
  steps:
  - script: |
      sudo python -m pip install wheel twine
    displayName: 'Install wheel+twine'
  - script: |
      docker pull quay.io/pypa/manylinux1_x86_64
      docker build -t pyboolector .
    displayName: 'Setup Docker Image'

  - script: |
      docker run -e BUILD_NUM=$(Build.BuildNumber) -v $(Build.Repository.LocalPath):/boolector pyboolector
    displayName: 'Run PyBoolector Build'

#  - task: TwineAuthenticate@1
#    condition: eq(variables['Build.SourceBranchName'], 'master')
#    inputs:
#      pythonUploadServiceConnection: pypi
  - script: |
      # Only deploy from master
      if test "$(Build.SourceBranchName)" = "master"; then
          python3.6 -m twine --version
          echo "Calling twine"
          python3.6 -m twine upload -r pyboolector --config-file $(PYPIRC_PATH) result/wheelhouse/* result/dist/*.tar.gz
          echo "Calling twine complete"
      fi
    displayName: 'Upload to PyPi'

